#!/usr/bin/env bash
# Render .agents/mcp/servers.json (canonical) into each agent's native MCP config.
#
#   .agents/scripts/sync-mcp.sh                 write .mcp.json, .cursor/mcp.json, .codex/config.toml
#   .agents/scripts/sync-mcp.sh check           change nothing; exit 1 if a generated file is stale
#   .agents/scripts/sync-mcp.sh install-codex   merge the servers into ${CODEX_HOME:-~/.codex}/config.toml
#
# servers.json maps a server name to one of:
#   {"type": "stdio", "command": "...", "args": ["..."], "env": {"KEY": "value"}}
#   {"type": "http", "url": "https://...", "headers": {"Name": "value"}}
# Anything else is rejected, so no agent silently gets a partial config. Requires jq
# (preinstalled on macOS 15+).
set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$AGENTS_DIR/.." && pwd)"
SOURCE="$AGENTS_DIR/mcp/servers.json"
PROJECT="sekisho"
HEADER="Generated by .agents/scripts/sync-mcp.sh from .agents/mcp/servers.json. Do not edit."

command -v jq >/dev/null || { echo "sync-mcp: jq is required" >&2; exit 1; }

# Validate servers.json and give every server an explicit type.
normalized() {
    jq '
      def fail($m): error("servers.json: " + $m);
      def strmap: type == "object" and all(.[]; type == "string");
      if type != "object" then fail("top level must be an object of servers") else . end
      | with_entries(
          .key as $n
          | if (.value | type) != "object" then fail("\($n): must be an object") else . end
          | .value |= (
              .type = (.type // (if has("url") then "http" else "stdio" end))
              | .type as $t
              | if ($t != "stdio" and $t != "http") then fail("\($n): type must be stdio or http") else . end
              | (keys - (if $t == "stdio" then ["type", "command", "args", "env"] else ["type", "url", "headers"] end)) as $extra
              | if ($extra | length) > 0
                then fail("\($n): unsupported field(s) for \($t): \($extra | join(", ")); extend sync-mcp.sh")
                else . end
              | if $t == "stdio" and (.command | type) != "string" then fail("\($n): stdio needs a command string") else . end
              | if $t == "http" and (.url | type) != "string" then fail("\($n): http needs a url string") else . end
              | if has("args") and ((.args | type) != "array" or any(.args[]; type != "string"))
                then fail("\($n): args must be an array of strings") else . end
              | if has("env") and (.env | strmap | not) then fail("\($n): env must map names to strings") else . end
              | if has("headers") and (.headers | strmap | not) then fail("\($n): headers must map names to strings") else . end
              | if any(.. | strings; test("\\$\\{"))
                then fail("\($n): ${...} interpolation differs per agent and is not supported yet")
                else . end
            )
        )
    ' "$SOURCE"
}

render_claude() { # Claude Code wants an explicit "type" for URL servers.
    jq '{mcpServers: .}'
}

render_cursor() { # Cursor infers the transport from "command" or "url".
    jq '{mcpServers: map_values(del(.type))}'
}

render_codex_tables() {
    jq -r '
      def tkey: if test("^[A-Za-z0-9_-]+$") then . else tojson end;
      def tval:  # JSON string escapes are also valid TOML basic-string escapes
        if type == "array" then "[" + (map(tval) | join(", ")) + "]"
        elif type == "object" then "{ " + (to_entries | map("\(.key | tkey) = \(.value | tval)") | join(", ")) + " }"
        else tojson end;
      to_entries[]
      | .key as $n | .value as $s
      | (if $s.type == "stdio"
         then [["command", $s.command], ["args", $s.args], ["env", $s.env]]
         else [["url", $s.url], ["http_headers", $s.headers]] end)
      | map(select(.[1] != null) | "\(.[0]) = \(.[1] | tval)")
      | "\n[mcp_servers.\($n | tkey)]\n" + join("\n")'
}

render_codex() {
    echo "# $HEADER"
    render_codex_tables
}

# write <relative path> <renderer>: render into the file, or compare in check mode.
stale=0
write() {
    local rel="$1" renderer="$2" tmp
    tmp="$(mktemp)"
    normalized | "$renderer" >"$tmp"
    if [ "$MODE" = check ]; then
        if ! cmp -s "$tmp" "$REPO_ROOT/$rel"; then
            echo "sync-mcp: $rel is stale (run .agents/scripts/sync-mcp.sh)" >&2
            stale=1
        fi
        rm -f "$tmp"
    else
        mkdir -p "$(dirname "$REPO_ROOT/$rel")"
        mv "$tmp" "$REPO_ROOT/$rel"
        echo "Wrote: $rel"
    fi
}

install_codex() {
    local config="${CODEX_HOME:-$HOME/.codex}/config.toml"
    local begin="# BEGIN $PROJECT managed MCP" end="# END $PROJECT managed MCP"
    local rest tmp name backup=""
    mkdir -p "$(dirname "$config")"
    touch "$config"
    rest="$(awk -v b="$begin" -v e="$end" '$0 == b {skip = 1; next} $0 == e {skip = 0; next} !skip' "$config")"
    # A second [mcp_servers.<name>] table would make the whole file invalid TOML.
    for name in $(normalized | jq -r 'keys[]'); do
        if printf '%s\n' "$rest" | grep -qE "^\[mcp_servers\.\"?$name\"?\]"; then
            echo "sync-mcp: $config already defines mcp_servers.$name outside the managed block; remove it first" >&2
            exit 1
        fi
    done
    tmp="$(mktemp)"
    {
        [ -n "$rest" ] && printf '%s\n\n' "$rest"
        echo "$begin"
        echo "# $HEADER"
        echo "# Relative paths resolve from the directory Codex starts in; run Codex from $REPO_ROOT."
        normalized | render_codex_tables
        echo "$end"
    } >"$tmp"
    if [ -s "$config" ]; then
        cp -p "$config" "$config.bak"
        backup=" (previous version saved as $config.bak)"
    fi
    mv "$tmp" "$config"
    echo "Updated: $config$backup"
}

MODE="${1:-apply}"
case "$MODE" in
    apply | check)
        write .mcp.json render_claude
        write .cursor/mcp.json render_cursor
        write .codex/config.toml render_codex
        exit "$stale"
        ;;
    install-codex) install_codex ;;
    *) echo "usage: $0 [check|install-codex]" >&2; exit 2 ;;
esac
